In [1]:
#sin fecha, con horarios, relacionada con la hora de los viajes y cuantos viajes por hora
#key = 00n + NOMBRE 
import pandas as pd 
estaciones_csv = pd.read_csv("estaciones_bicis .csv")
estaciones_csv.head()

,ID,NUMERO,NOMBRE,DIRECCION,BARRIO,COMUNA,EMPLAZAMIENTO,ANCLAJES,QUEDA ABIERTA,Latitud,Longitud
0,202,1,FACULTAD DE DERECHO,"2120 Figueroa Alcorta, Pres. Av.",RECOLETA,COMUNA 2,VEREDA,30.0,1,-34.5842,-58.3905
1,2,2,RETIRO I,"Ramos Mejia, Jose Maria, Dr. Av. & Del Liberta...",RETIRO,COMUNA 1,PLAZA ABIERTA,36.0,1,-34.5927,-58.3751
2,3,3,ADUANA,Moreno & Azopardo,MONSERRAT,COMUNA 1,VEREDA,20.0,1,-34.6112,-58.3696
3,4,4,PLAZA ROMA,Lavalle & Bouchard,SAN NICOLAS,COMUNA 1,CALZADA,20.0,1,-34.6018,-58.3691
4,5,5,PLAZA ITALIA,2601 Sarmiento Av.,PALERMO,COMUNA 14,VEREDA,42.0,1,-34.5808,-58.4204

In [10]:
estaciones_csv.columns

Index(['ID', 'NUMERO', 'NOMBRE', 'DIRECCION', 'BARRIO', 'COMUNA',
       'EMPLAZAMIENTO', 'ANCLAJES', 'QUEDA ABIERTA', 'Latitud', 'Longitud'],
      dtype='object')

In [21]:
def crearFormatID(fila):
    #La funcion devuelve la cadena concatenada de el indice con 3 cifras y el nombre
    id = str(fila[0]).zfill(3)
    return f"{str(id)} - {str(fila[2])}"

In [23]:
estaciones_csv["FormatId"] = estaciones_csv.apply(crearFormatID, axis=1)
nuevo_df = estaciones_csv["FormatId"]

In [24]:
nuevo_df.head()

0    202 - FACULTAD DE DERECHO
1               002 - RETIRO I
2                 003 - ADUANA
3             004 - PLAZA ROMA
4           005 - PLAZA ITALIA
Name: FormatId, dtype: object

In [25]:
marzo = pd.read_csv("marzo_dataset .csv")

In [26]:
marzo.head()

,Id_recorrido,duracion_recorrido,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,id_estacion_destino,nombre_estacion_destino,id_usuario,género
0,17415328BAEcobici,520,2023-03-04 15:17:55,130BAEcobici,130 - RETIRO II,448BAEcobici,393 - Barrio 31,444458BAEcobici,FEMALE
1,17599063BAEcobici,847,2023-03-22 16:32:46,440BAEcobici,142 - ARMENIA,58BAEcobici,058 - Ministro Carranza,711954BAEcobici,OTHER
2,17575845BAEcobici,"2,084",2023-03-20 19:23:56,94BAEcobici,094 - GÚZMAN,236BAEcobici,254 - Plaza Rafael Hernandez,964367BAEcobici,MALE
3,17665972BAEcobici,476,2023-03-29 13:23:15,158BAEcobici,158 - VILLARROEL,206BAEcobici,159 - Fitz Roy & Gorriti,47678BAEcobici,FEMALE
4,17425224BAEcobici,"1,136",2023-03-06 08:33:28,116BAEcobici,116 - HOSPITAL ALEMÁN,114BAEcobici,114 - DELLA PAOLERA,2540BAEcobici,MALE

In [28]:
marzo['fecha_origen_recorrido'] = pd.to_datetime(marzo['fecha_origen_recorrido'])

In [31]:
marzo['hora_origen'] = marzo['fecha_origen_recorrido'].dt.hour

In [32]:
marzo.head()

,Id_recorrido,duracion_recorrido,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,id_estacion_destino,nombre_estacion_destino,id_usuario,género,hora_origen
0,17415328BAEcobici,520,2023-03-04 15:17:55,130BAEcobici,130 - RETIRO II,448BAEcobici,393 - Barrio 31,444458BAEcobici,FEMALE,15
1,17599063BAEcobici,847,2023-03-22 16:32:46,440BAEcobici,142 - ARMENIA,58BAEcobici,058 - Ministro Carranza,711954BAEcobici,OTHER,16
2,17575845BAEcobici,"2,084",2023-03-20 19:23:56,94BAEcobici,094 - GÚZMAN,236BAEcobici,254 - Plaza Rafael Hernandez,964367BAEcobici,MALE,19
3,17665972BAEcobici,476,2023-03-29 13:23:15,158BAEcobici,158 - VILLARROEL,206BAEcobici,159 - Fitz Roy & Gorriti,47678BAEcobici,FEMALE,13
4,17425224BAEcobici,"1,136",2023-03-06 08:33:28,116BAEcobici,116 - HOSPITAL ALEMÁN,114BAEcobici,114 - DELLA PAOLERA,2540BAEcobici,MALE,8

In [33]:
marzo.sort_values('nombre_estacion_origen')

,Id_recorrido,duracion_recorrido,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,id_estacion_destino,nombre_estacion_destino,id_usuario,género,hora_origen
3856,17537503BAEcobici,"2,075",2023-03-16 15:32:14,202BAEcobici,001 - FACULTAD DE DERECHO,12BAEcobici,012 - Plaza Vicente Lopez,967324BAEcobici,MALE,15
6870,17624202BAEcobici,"2,024",2023-03-25 12:39:35,202BAEcobici,001 - FACULTAD DE DERECHO,242BAEcobici,103 - MALBA,678770BAEcobici,MALE,12
7034,17497211BAEcobici,"1,533",2023-03-13 07:52:05,202BAEcobici,001 - FACULTAD DE DERECHO,65BAEcobici,065 - Julián Álvarez,960552BAEcobici,FEMALE,7
2235,17473542BAEcobici,123,2023-03-09 21:30:59,202BAEcobici,001 - FACULTAD DE DERECHO,202BAEcobici,001 - FACULTAD DE DERECHO,962186BAEcobici,MALE,21
7155,17582427BAEcobici,"1,651",2023-03-21 11:32:38,202BAEcobici,001 - FACULTAD DE DERECHO,121BAEcobici,121 - YATAY,142019BAEcobici,MALE,11
...,...,...,...,...,...,...,...,...,...,...
3746,17545956BAEcobici,363,2023-03-17 07:47:10,268BAEcobici,399 - GARCIA DEL RIO,487BAEcobici,239 - AVENIDA CRAMER,411731BAEcobici,FEMALE,7
8402,17398957BAEcobici,830,2023-03-02 20:06:26,268BAEcobici,399 - GARCIA DEL RIO,423BAEcobici,043 - PLAZA ALBERDI,400037BAEcobici,OTHER,20
6007,17377404BAEcobici,408,2023-03-01 07:08:09,268BAEcobici,399 - GARCIA DEL RIO,487BAEcobici,239 - AVENIDA CRAMER,83322BAEcobici,MALE,7
3708,17690230BAEcobici,"1,871",2023-03-31 13:00:02,268BAEcobici,399 - GARCIA DEL RIO,268BAEcobici,399 - GARCIA DEL RIO,823279BAEcobici,FEMALE,13
1824,17620578BAEcobici,810,2023-03-24 16:02:04,268BAEcobici,399 - GARCIA DEL RIO,275BAEcobici,256 - PLAZA NORUEGA,685719BAEcobici,FEMALE,16

In [35]:
origen_marzo_por_hora = marzo[['Id_recorrido','nombre_estacion_origen','hora_origen']]
origen_marzo_por_hora.head()

        Id_recorrido nombre_estacion_origen  hora_origen
0  17415328BAEcobici        130 - RETIRO II           15
1  17599063BAEcobici          142 - ARMENIA           16
2  17575845BAEcobici           094 - GÚZMAN           19
3  17665972BAEcobici       158 - VILLARROEL           13
4  17425224BAEcobici  116 - HOSPITAL ALEMÁN            8

In [36]:
origen_marzo_por_hora.sort_values('nombre_estacion_origen')

           Id_recorrido     nombre_estacion_origen  hora_origen
3856  17537503BAEcobici  001 - FACULTAD DE DERECHO           15
6870  17624202BAEcobici  001 - FACULTAD DE DERECHO           12
7034  17497211BAEcobici  001 - FACULTAD DE DERECHO            7
2235  17473542BAEcobici  001 - FACULTAD DE DERECHO           21
7155  17582427BAEcobici  001 - FACULTAD DE DERECHO           11
...                 ...                        ...          ...
3746  17545956BAEcobici       399 - GARCIA DEL RIO            7
8402  17398957BAEcobici       399 - GARCIA DEL RIO           20
6007  17377404BAEcobici       399 - GARCIA DEL RIO            7
3708  17690230BAEcobici       399 - GARCIA DEL RIO           13
1824  17620578BAEcobici       399 - GARCIA DEL RIO           16

[10000 rows x 3 columns]

In [39]:
origen_marzo_por_hora.groupby(['nombre_estacion_origen', 'hora_origen']).size().reset_index(name='viajes_por_hora_y_estacion')

         nombre_estacion_origen  hora_origen  viajes_por_hora_y_estacion
0     001 - FACULTAD DE DERECHO            1                           1
1     001 - FACULTAD DE DERECHO            3                           1
2     001 - FACULTAD DE DERECHO            5                           2
3     001 - FACULTAD DE DERECHO            7                           2
4     001 - FACULTAD DE DERECHO            8                           2
...                         ...          ...                         ...
4196       399 - GARCIA DEL RIO           16                           4
4197       399 - GARCIA DEL RIO           18                           3
4198       399 - GARCIA DEL RIO           20                           4
4199       399 - GARCIA DEL RIO           21                           2
4200       399 - GARCIA DEL RIO           23                           1

[4201 rows x 3 columns]